### ISSUE TITLE
installation of headers

### ISSUE THREAD

**Issue by philip-davis** [SCOREC/pcms#118]
Public header `wdmcpl.h` includes several headers that aren't installed:

```
#include "wdmcpl/coordinate_systems.h"
#include <unordered_map>
#include "wdmcpl/assert.h"
#include "wdmcpl/external/span.h"
#include "wdmcpl/types.h"
```

I have been working around this by adding:
```
install(DIRECTORY wdmcpl
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
```
to `src/CMakeLists.txt` to just wholesale copy the directory.

**Comment by jacobmerson** [comment]
Thanks. I wasn't super careful about header installation (and I have been running tests w/o install). I will make sure to update the CMakeLists.txt
